In [8]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

#dense layer 
class layer_dense:
    #Layer Initialization
    def __init__(self, n_inputs, n_neurons):
        #initialize weights and biases
        self.weights=0.01*np.random.randn(n_inputs, n_neurons)
        self.biases=np.zeros((1, n_neurons))

    #Forward Pass 
    def forward(self,inputs):
        # calculate output values from inputs, weights and biases
        self.output=np.dot(inputs, self.weights)+self.biases 

# Create dataset
X,y=spiral_data(samples=100, classes=3)
#create dense layer with 2 input features and 3 output values 
dense1=layer_dense(2,3)
#perform a forward pass of our training data through this layer 
dense1.forward(X)
# lets see output of the first few samples 
print(dense1.output[:5])





[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]
