In [8]:
#cross entropy loss building blocks in python
import numpy as np
softmax_outputs=np.array([
    [0.7, 0.1,0.2],
    [0.1, 0.5,0.4],
    [0.02,0.9,0.08],

])
class_targets= [0,1,1]
print(softmax_outputs[[0,1,2], class_targets])

[0.7 0.5 0.9]


In [9]:
print(-np.log(softmax_outputs[
    range(len(softmax_outputs)),class_targets
]))
neg_log=-np.log(softmax_outputs[
    range(len(softmax_outputs)),class_targets
])
average_loss=np.mean(neg_log)
print(average_loss)

[0.35667494 0.69314718 0.10536052]
0.38506088005216804


In [10]:
Y_true_check=np.array([
    [1,0,0],
    [0,1,0],
    [0,1,0]
])

y_pred_clipped_check=np.array([
    [0.7,0.2,0.1],
    [0.1,0.5,0.4],
    [0.02,0.9,0.08]
])

A=Y_true_check*y_pred_clipped_check
B=np.sum(A, axis=1)
C=-np.log(B)
print(C)

print (np.mean(C))

[0.35667494 0.69314718 0.10536052]
0.38506088005216804


In [13]:
#Implementing the categorical cross entropy class
#cross entropy loss
class Loss_categoricalcrossentropy(loss):
    #Forward pass
    def forward(self, y_pred, y_true):
        #Number of samples in a batch
        samples=len(y_pred)
        #clip data to prevent division by 0
        # clip both sides to not drag mean towards any value
        y_pred_clipped=np.clip(y_pred, 1e-7, 1-1e-7)
        #Probabilites for target values-
        #Only if Categorical labels
        if len(y_true.shape)==1:
            correct_confidences=y_pred_clipped[
                range(samples),
                y_true
            ]
        #Mask values-only for one encoded labels
        elif len(y_true.shape)==2:
            correct_confidences=np.sum(
                y_pred_clipped*y_true,
                axis=1
            )
            #Losses
            negative_log_likelihoods=-np.log(correct_confidences)
            return negative_log_likelihoods

In [14]:
#Implementing Loss Class
#Common Loss Class

class loss:
    #Calculates the data and regularization losses 
    # Given model output and grounf truth values 
    def calculate(self,output,y):
        #Calculate sample Losses
        sample_losses=self.forward(output,y)
        #calculate mean loss
        data_loss=np.mean(sample_losses)
        #return loss
        return data_loss

In [15]:
softmax_outputs=np.array([
    [0.7,0.1,0.2],
    [0.1,0.5,0.4],
    [0.02,0.9,0.08]
])
class_targets=np.array([
    [1,0,0],
    [0,1,0],
    [0,1,0]
])
loss_function=Loss_categoricalcrossentropy()
loss=loss_function.calculate(softmax_outputs,class_targets)
print(loss)

0.38506088005216804
