In [9]:
import numpy as np

class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs, self.weights) + self.biases




class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)


# Softmax Activation 
class Activation_softmax:
    #forward pass
    def forward(self, inputs):
        #Get unnormalized probabilities 
        exp_values=np.exp(inputs-np.max(inputs, axis=1, keepdims=True))
        #normalize them for each sample 
        probabilities=exp_values/np.sum(exp_values, axis=1, keepdims=True)
        self.output=probabilities


        

In [15]:
#Implementing Loss Class
#Common Loss Class

class loss:
    #Calculates the data and regularization losses 
    # Given model output and grounf truth values 
    def calculate(self,output,y):
        #Calculate sample Losses
        sample_losses=self.forward(output,y)
        #calculate mean loss
        data_loss=np.mean(sample_losses)
        #return loss
        return data_loss

In [19]:
#Implementing the categorical cross entropy class
#cross entropy loss
class Loss_categoricalcrossentropy(loss):
    #Forward pass
    def forward(self, y_pred, y_true):
        #Number of samples in a batch
        samples=len(y_pred)
        #clip data to prevent division by 0
        # clip both sides to not drag mean towards any value
        y_pred_clipped=np.clip(y_pred, 1e-7, 1-1e-7)
        #Probabilites for target values-
        #Only if Categorical labels
        if len(y_true.shape)==1:
            correct_confidences=y_pred_clipped[
                range(samples),
                y_true
            ]
        #Mask values-only for one encoded labels
        elif len(y_true.shape)==2:
            correct_confidences=np.sum(
                y_pred_clipped*y_true,
                axis=1
            )
        #Losses
        negative_log_likelihoods=-np.log(correct_confidences)
        return negative_log_likelihoods

In [24]:
import numpy as np
from nnfs.datasets import spiral_data
# Create dataset
X,y=spiral_data(samples=100, classes=3)
#create dense layer with 2 input features and 3 output values 
dense1=Layer_Dense(2,3)

# create relu activation to be used with dense layer 
activation1=Activation_ReLU()
# create second dense layer with 3 input features(as we take output of previous layer here) and 3 output values 
dense2=Layer_Dense(3,3)
#create softmax activation to be used with dense layer:
activation2=Activation_softmax()

#Create Loss Function
loss_function=Loss_categoricalcrossentropy()

#make a forward pass of our training data through  this layer 
dense1.forward(X)
#make a forward pass through activation function 
# it takes the output of first dense layer here 
activation1.forward(dense1.output)
#make a forward pass through second dense layer
#it takes outputs of activations fuction as first layer  of input 
dense2.forward(activation1.output)
#make a forward pas through activation function
#it takes the output of second dense layer here
activation2.forward(dense2.output)
#lets see the output of the first few samples 
print(activation2.output[:5])

#Perform a forward pass through activation function
#it takes the output of second dense layer here and return loss 
loss=loss_function.calculate(activation2.output,y)
#print loss value 
print('loss:',loss)


#Calculate Accuracy from Output of activation and targets 
#Calculate values Along First Axis 

predictions=np.argmax(activation2.output, axis=1)
if len(y.shape)==2:
    y=np.argmax(y,axis=1)

#calculate accuracy
accuracy=np.mean(predictions==y)

    #print Accuracy
print('acc:', accuracy) 

[[0.33333333 0.33333333 0.33333333]
 [0.33333282 0.33333344 0.33333374]
 [0.33333159 0.33333364 0.33333477]
 [0.33333141 0.33333374 0.33333485]
 [0.33333119 0.33333379 0.33333502]]
loss: 1.0986104476544531
acc: 0.35
