In [1]:
#Activation Function
import numpy as np
A=[[1,2,3], [4,5,6], [7,8,9]]
print(np.sum(A))

print(np.sum(A, axis=1))
print(np.sum(A, axis=1).shape)

print (np.sum(A, axis=0, keepdims=True))
print(np.sum(A, axis=0, keepdims=True).shape)

print(np.sum(A, axis=1, keepdims=True))
print(np.sum(A, axis=1, keepdims=True).shape)



45
[ 6 15 24]
(3,)
[[12 15 18]]
(1, 3)
[[ 6]
 [15]
 [24]]
(3, 1)
