In [3]:
#ACTIVATION FUNCTION:RELU
import numpy as np  
from nnfs.datasets import spiral_data
inputs=[0,2,-1, 3.3, -2.7, 1.1, 2.2, -100]
output=np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [14]:
# RELU ACTIVATION
class Activation_ReLU:
    # FORWARD PASS
    def forward(self, inputs):
        # calculate output values from input
        self.output = np.maximum(0, inputs)


# DENSE LAYER
class Layer_Dense:
    # Layer Initialization
    def __init__(self, n_inputs, n_neurons):
        # initialize weights and biases
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))

    # Forward Pass
    def forward(self, inputs):
        # calculate output values from inputs, weights and biases
        self.output = np.dot(inputs, self.weights) + self.biases

In [17]:
# Create dataset
X,y=spiral_data(samples=100, classes=3)
#create dense layer with 2 input features and 3 output values 
dense1=layer_dense(2,3)

# create relu activation to be used with dense layer 
activation1=Activation_ReLU()
# make a forward pass of our training data through this layer 
dense1.forward(X)
#forward pass through activation func.
# takes in output from previous layer 

activation1.forward(dense1.output)
# lets see output of a few samples 
print(activation1.output[:5])


[[0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.06025159e-04 0.00000000e+00]
 [0.00000000e+00 2.24725587e-04 0.00000000e+00]
 [3.50080270e-05 3.08102525e-04 0.00000000e+00]
 [0.00000000e+00 4.41117083e-04 0.00000000e+00]]
